apiVersion: v1
kind: ConfigMap
metadata:
  name: config-postgres
data:
  001-init-chirpstack_ns.sh: |
    #!/bin/bash
    set -e

    psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
        create role chirpstack_ns with login password 'chirpstack_ns';
        create database chirpstack_ns with owner chirpstack_ns;
    EOSQL

  002-init-chirpstack_as.sh: |
    #!/bin/bash
    set -e

    psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
        create role chirpstack_as with login password 'chirpstack_as';
        create database chirpstack_as with owner chirpstack_as;
    EOSQL

  003-chirpstack_as_trgm.sh: |
    #!/bin/bash
    set -e

    psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname="chirpstack_as" <<-EOSQL
        create extension pg_trgm;
    EOSQL

  004-chirpstack_as_hstore.sh: |
    #!/bin/bash
    set -e

    psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname="chirpstack_as" <<-EOSQL
        create extension hstore;
    EOSQL
